INSERT INTO USER(ID, USER_NAME, PASSWORD, FULL_NAME, EMAIL_ADDRESS, ACTIVE, ADMIN) VALUES(1, 'lib', '$2a$11$Bd/BGzf7iJyyXRXi7ush8Oy.Gsw2zFiQJAijIhmeQ5BOt3UL7MBB2', 'librarian', 'lib@test.test', true, true);
INSERT INTO USER(ID, USER_NAME, PASSWORD, FULL_NAME, EMAIL_ADDRESS, ACTIVE, ADMIN) VALUES(2, 'test', '$2a$11$Bd/BGzf7iJyyXRXi7ush8Oy.Gsw2zFiQJAijIhmeQ5BOt3UL7MBB2', 'test user', 'test@test.test', true, false);
INSERT INTO USER(ID, USER_NAME, PASSWORD, FULL_NAME, EMAIL_ADDRESS, ACTIVE, ADMIN) VALUES(3, 'test2', '$2a$11$Bd/BGzf7iJyyXRXi7ush8Oy.Gsw2zFiQJAijIhmeQ5BOt3UL7MBB2', 'test user2', 'test2@test.test', true, false);

INSERT INTO BOOK(ID, TITLE, AMOUNT) VALUES(1, 'Amazing Book', 2);
INSERT INTO BOOK(ID, TITLE, AMOUNT) VALUES(2, 'Less Amazing Book', 3);

INSERT INTO BORROW(ID, START_DATE, END_DATE, BOOK_ID, USER_ID) VALUES(1, '2020-01-01', '2020-02-01', 1, 2);
INSERT INTO BORROW(ID, START_DATE, END_DATE, BOOK_ID, USER_ID) VALUES(2, '2020-01-01', '2020-02-01', 2, 2);
INSERT INTO BORROW(ID, START_DATE, END_DATE, BOOK_ID, USER_ID) VALUES(3, '2020-01-01', '2020-02-01', 1, 3);

INSERT INTO SUBSCRIPTION(ID, USER_ID, BOOK_ID) VALUES(1, 2, 1);
INSERT INTO SUBSCRIPTION(ID, USER_ID, BOOK_ID) VALUES(2, 2, 2);
INSERT INTO SUBSCRIPTION(ID, USER_ID, BOOK_ID) VALUES(3, 3, 1);
INSERT INTO SUBSCRIPTION(ID, USER_ID, BOOK_ID) VALUES(4, 3, 2);